### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by mratsim** [ftynse/clint#3]
I manage to build Clint but had a couple issues:

1. Clay "parser.h" no such file or directory

![image](https://user-images.githubusercontent.com/22738317/57181475-83fb2400-6e94-11e9-8ce0-a372328f340a.png)

No amount of fiddling the includes work, but compiling from clay directory directly did. Strange

2. C++14 needs to be enforced
Otherwise I get a series of type errors that starts from an `auto`

```
/home/beta/Programming/Polyhedral_compilers/clint/vizpolyhedron.cpp:604:62: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
#      PointMap::iterator found = std::find_if(it, eit, [point](auto p) { return p.second == point; });
                                                                ^~~~
/home/beta/Programming/Polyhedral_compilers/clint/vizpolyhedron.cpp: In lambda function:
/home/beta/Programming/Polyhedral_compilers/clint/vizpolyhedron.cpp:604:81: error: request for member ‘second’ in ‘p’, which is of non-class type ‘int’
     PointMap::iterator found = std::find_if(it, eit, [point](auto p) { return p.second == point; });
```

**Comment by ftynse** [comment]
Thanks for the report!

> Clay "parser.h" no such file or directory

It sounds like a problem in Clay itself, does it build on its own?

> C++14 needs to be enforced

Since you seem to have managed to fix that, you are very welcome to submit a patch!

**Comment by mratsim** [comment]
Yes I can build Clay if I cd into its vendor directly and `make` from there
